### ISSUE TITLE
Enable HTML snippets for markdown files

### ISSUE THREAD

**Issue by jnalldr** [lonekorean/atom-autocomplete-font-awesome#10]
How can I enable the snippet autocomplete when using this to create markdown files?  I use HEXO as my static website generator, all content is done in markdown.  (File types are .md)

**Comment by jnalldr** [comment]
Nevermind, I found that I just needed to edit the snippets-provider.js file to work for .source.gfm instead of .text.html

Works great!

**Comment by lonekorean** [comment]
Glad you found a workaround. Yeah, I generally try to limit where autocomplete is enabled because I don't want this plug-in to get obnoxious and give suggestions in irrelevant places. Thanks for cluing me into your use case though. I'll consider it (maybe as an option?) for a future release.
