### ISSUE TITLE
Support for slim files?

### ISSUE THREAD

**Issue by blimey85** [lonekorean/atom-autocomplete-font-awesome#3]
I primarily develop in Ruby on Rails and my view files are all in slim format. I tested your plugin and it works great within an html file, but doesn't fire when in a slim file. The output I need in slim is:
`i.fa.fa-calendar`
but just having the plugin fire and let me select which icon I want, would be great. I could then swap the code for what I need since I'm primarily wanting it just to let me quickly look through the available icons. If there is a way to have this trigger and output different code, specific to slim, I would deff be willing to set that up and create a PR.

**Comment by lonekorean** [comment]
Hi, thanks for the comment.

You've got me thinking. I had purposefully limited the situations where this autocomplete kicks in. I didn't want it popping up when irrelevant and being annoying. But maybe the "fa-" prefix is unique enough that this isn't really a problem?

I'm not familiar with Ruby or this slim format. What filename extension(s) would this cover?

They syntax you described seems similar to other formats like Jade and Haml, so your request could help others, too.

Thanks a bunch!

**Comment by lonekorean** [comment]
I went for it. The autocomplete should work in all file types now. Let me know if it doesn't.

**Comment by blimey85** [comment]
Just updated and tried it and it works great. Well done!
