### ISSUE TITLE
Icons preview not correctly working

### ISSUE THREAD

**Issue by Arcesilas** [lonekorean/atom-autocomplete-font-awesome#4]
Hi,

Thanks for the package! However, I don't have the icons preview working. Here's what I get:
![screenshot-fa-autocomplete](https://user-images.githubusercontent.com/5526263/31856246-6c5368f8-b6bc-11e7-8711-f9e86780513b.png)

Am I missing something obvious? Is there an additionnal package required for the fonts to be displayed?

Running Atom 1.21.1 x64 (latest stable) on Linux Fedora 26.

Thanks!

**Comment by lonekorean** [comment]
Hey, thanks for the report. No, there are no other prereq packages, so something is awry.

Can you try turning off your other packages/themes? Something in them might be overriding the style that tells it to use the Font Awesome font where the previews should be.

If that doesn't work, can you check that this file exists?

`~/.atom/packages/autocomplete-font-awesome/node_modules/font-awesome/less/font-awesome.less`

That's a Mac path, but hopefully similar for Linux. It should exist (and with sensible permissions), but if not then that would point to an installation/permission error.

Thanks!

**Comment by Arcesilas** [comment]
Hi, thanks for your answer!

So I checked the dependencies and Font Awesome node module is correctly installed.
Temporarily removed my ~/.atom folder and started Atom with no package installed. Installed autocomplete-font-awesome and... same problem.
Tried to replace the fonts with the ones I have in my website source, and the problem is the same.
I can't display the fonts with the Font Manager I have (which is... font-manager 0.7.2 on Linux Fedora 26), but the fonts seem to be correctly loaded (the license displayed in font manager is indeed correct).

It's not a blocking problem, but I must say that the icons preview is a must have feature that I found only in your package...

If you have any other idea, please let me know (not necessarily how to actually solve the problem, but maybe at least if there can be a conflict, where I can search...). I keep searching anyway.

**Comment by Arcesilas** [comment]
Hey,

Solved... Had to install the font on my computer (it's in the Fedora Repository).
Thanks for your time, sorry for the inconvenience!

**Comment by lonekorean** [comment]
Glad you got it working, but that is definitely a bug. The package should be loading its own copy of the font file from `~/.atom/packages/autocomplete-font-awesome/node_modules/font-awesome/fonts`.

I'll log a bug for this. Thanks for the heads up!

**Comment by lonekorean** [comment]
I was able to reproduce on Ubuntu 16.04. Fixed with version 0.2.3.

Thanks again for all your help, if there are any lingering issues please let me know.

**Comment by Arcesilas** [comment]
Hi!
Glad you could reproduce the bug and fix it!
Thanks! (even if I fixed the problem by installing the font from the Linux packages)
