### ISSUE TITLE
autocomplete-font-awesome for markdown files does not work

### ISSUE THREAD

**Issue by KevCaz** [lonekorean/atom-autocomplete-font-awesome#7]
Hi @lonekorean, 

Your atom package is very helpful and works fine on my side (debian 9 / atom 1.23.3). I however often use fa icons in markdown files (*i.e.* `.source.gfm`) but the snippets does not kick in for them. I acknowledge that you have activated the snippets for all kind of files (#3) and I have tested whether I was able to use your package on a large range of files (`.haml`, `.c`, `.html`, `.rb`, ...) and it works fine but it does not when the scope is `.source.gfm`. 

Is-this expected? If it works on your side I'll investigate on mine :). 

Anyway, thanks for your work on this package.

**Comment by lonekorean** [comment]
Hm, icon suggestions should work in any file. I just tried in a file saved as `test.md` and it worked for me (Mac / v1.23.3).

If you're talking specifically about snippets though (the ones that expand into HTML) those only work in certain HTML contexts.

**Comment by KevCaz** [comment]
Thanks for the quick answer, 

> icon suggestions should work in any file. 

I was talking about icon suggestion indeed. 

> I just tried in a file saved as test.md and it worked for me (Mac / v1.23.3).

Thanks! I guess this means the issues is related with my config then. I am closing this issue given that it is likely not due to your code.

**Comment by lonekorean** [comment]
Ok, if you see any more evidence that it might be something in my code, please let me know. Thanks!

**Comment by KevCaz** [comment]
Sure, 

my guess is that I did something wrong with `autocomplete-plus`... :)

**Comment by KevCaz** [comment]
Sounds like my issue is due to another package: the autocomplete-bibtex package and sounds like it will be solved soon! https://github.com/apcshields/autocomplete-bibtex/issues/90
